In [2]:
!pip install pysimplegui

In [1]:
import os
import numpy as np
import pandas as pd
import re
from matplotlib import pyplot as plt
import fitz # From PyMuPDF
from PIL import Image
import cv2
import argparse
import imutils
import sys
import PySimpleGUI as sg
import random

In [2]:
os.chdir(r'D:\Dropbox\Proyectos\python\formatos_elecciones')
# os.chdir(r'C:\Users\gd.orbegozo10\Dropbox\Cosas_Programacion\Python\python\formatos_elecciones')

In [3]:
digit_dir = 'test/save_images'
digit_list = os.listdir(digit_dir)

digit_name = digit_list[random.randint(0, len(digit_list))]

In [5]:
digit_split = digit_name.split('_')
d = int(digit_split[0])
n_form = int(digit_split[1])
depto = int(digit_split[5])
mpio = int(digit_split[6])
zona = int(digit_split[7])
mesa = int(digit_split[10])

In [6]:
digit_img = cv2.imread(f'{digit_dir}/{digit_name}')

In [37]:
%%python
import tkinter as tk
screen = tk.Tk()
screen.title("Matplot Graphies")
screen.geometry("500x500")

label = tk.Label(
    text="Nombre",
    fg="black",
    bg="#34A2FE",
    width=20,
    height=10
)

button = tk.Button(
    text="Click me!",
    width=25,
    height=5,
    bg="blue",
    fg="yellow",
)

entry = tk.Entry(
    fg="black", 
    bg="white", 
    width=50
)

label.pack()
button.pack()
entry.pack()

name = entry.get()
print(name)

screen.mainloop()

---

In [134]:
top_text = sg.Text(f'FORMULARIO {n_form}, DÍGITO {d}. \nDepto: {depto}, Mpio: {mpio}, Zona: {zona}, Mesa: {mesa}')
image_elem1 = sg.Image(digit_img)
digit_text = sg.Text('Insertar dígito de la imagen:')

layout=[
    [top_text],
    [image_elem1],
    [digit_text, sg.InputText()],
    [sg.Button('OK')],
    [sg.Button('Está mal recortado')],
    [sg.Button('Es un número malo')]
]

window = sg.Window('Window Title', layout)    

# Create an event loop
while True:
    event, values = window.read()
    # End program if user closes window or
    # presses the OK button
    if event == "Exit" or event == sg.WIN_CLOSED:
        break
    print(values)
window.close()


TclError: couldn't open "[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]": no such file or directory

In [36]:
layout = [[sg.Text('My one-shot window.')],      
                 [sg.InputText()],      
                 [sg.Submit(), sg.Cancel()]]      

window = sg.Window('Window Title', layout)    

event, values = window.read()    
window.close()

text_input = values[0]    
sg.popup('You entered', text_input)

'OK'

In [29]:
window = sg.Window("Image Viewer", layout)
# Run the Event Loop
while True:
    event, values = window.read()
    if event == "Exit" or event == sg.WIN_CLOSED:
        break
    # Folder name was filled in, make a list of files in the folder
    if event == "-FOLDER-":
        folder = values["-FOLDER-"]
        try:
            # Get list of files in folder
            file_list = os.listdir(folder)
        except:
            file_list = []

        fnames = [
            f
            for f in file_list
            if os.path.isfile(os.path.join(folder, f))
            and f.lower().endswith((".png", ".gif"))
        ]
        window["-FILE LIST-"].update(fnames)
    elif event == "-FILE LIST-":  # A file was chosen from the listbox
        try:
            filename = os.path.join(
                values["-FOLDER-"], values["-FILE LIST-"][0]
            )
            window["-TOUT-"].update(filename)
            window["-IMAGE-"].update(filename=filename)

        except:
            pass

window.close()

In [24]:
# img_viewer.py

import PySimpleGUI as sg
import os.path

# First the window layout in 2 columns

file_list_column = [
    [
        sg.Text("Image Folder"),
        sg.In(size=(25, 1), enable_events=True, key="-FOLDER-"),
        sg.FolderBrowse(),
    ],
    [
        sg.Listbox(
            values=[], enable_events=True, size=(40, 20), key="-FILE LIST-"
        )
    ],
]

# For now will only show the name of the file that was chosen
image_viewer_column = [
    [sg.Text("Choose an image from list on left:")],
    [sg.Text(size=(40, 1), key="-TOUT-")],
    [sg.Image(key="-IMAGE-")],
]

# ----- Full layout -----
layout = [
    [
        sg.Column(file_list_column),
        sg.VSeperator(),
        sg.Column(image_viewer_column),
    ]
]

window = sg.Window("Image Viewer", layout)

# Run the Event Loop
while True:
    event, values = window.read()
    if event == "Exit" or event == sg.WIN_CLOSED:
        break
    # Folder name was filled in, make a list of files in the folder
    if event == "-FOLDER-":
        folder = values["-FOLDER-"]
        try:
            # Get list of files in folder
            file_list = os.listdir(folder)
        except:
            file_list = []

        fnames = [
            f
            for f in file_list
            if os.path.isfile(os.path.join(folder, f))
            and f.lower().endswith((".png", ".gif"))
        ]
        window["-FILE LIST-"].update(fnames)
    elif event == "-FILE LIST-":  # A file was chosen from the listbox
        try:
            filename = os.path.join(
                values["-FOLDER-"], values["-FILE LIST-"][0]
            )
            window["-TOUT-"].update(filename)
            window["-IMAGE-"].update(filename=filename)

        except:
            pass

window.close()

----

In [34]:

d = 0
depto = 0
mpio = 0
zona = 0
mesa = 0
# Dejar el layout
top_image_viewer = [
     [
        sg.Text("Image Folder"),
        sg.In(size=(25, 1), enable_events=True, key="-FOLDER-"),
        sg.FolderBrowse(),
    ],
    [
        sg.Listbox(
            values=[], enable_events=True, size=(40, 20), key="-FILE LIST-"
        )
    ],
    [sg.Text(f"DÍGITO {d} DEL FORMULARIO E_14.")],
    [sg.Text(f"Depto: {depto}, Mpio: {mpio}, Zona: {zona}, Mesa: {mesa}")],
    [sg.Image(key="-IMAGE-")],
]

bottom_panel = [
    [sg.Text("La imagen de arriba es el dígito:"), sg.InputText()],
    [sg.Button("Mal recortado")],
    [sg.Button("Número tachado")],
]
